---
- name: Install nginx
  become: true
  package:
    name: 
      - nginx
      - apache2-utils
    state: present

- name: Create nginx directory
  become: true
  file:
    path: /var/nginx
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Create nginx/html directory
  become: true
  file:
    path: /var/nginx/html
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data

- name: Copy index.html
  become: true
  template: src=index.html dest=/var/nginx/html

- name: Set index.html owner
  become: true
  file:
    path: /var/nginx/html/index.html
    owner: www-data
    group: www-data

- name: Remove index.nginx-debian.html
  become: true
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- name: Copy nginx file
  become: true
  template: src=default.conf dest=/etc/nginx/sites-enabled/default
  notify: restart nginx

- name: Create files directory
  become: true
  file:
    path: /var/nginx/html/files
    state: directory
    mode: '0777'
    owner: www-data
    group: www-data

- name: Check for htpasswd file
  become: true
  stat:
    path: /var/nginx/.htpasswd
  register: htpasswd_file

- name: Create htpasswd file
  become: true
  command: htpasswd -bc /var/nginx/.htpasswd {{ www_user }} {{ www_password }}
  when: htpasswd_file.stat.exists == false

- name: Set nginx ownership
  become: true
  file:
    path: /var/nginx
    owner: www-data
    group: www-data

- name: Restart nginx
  become: true
  service:
    name: nginx
    state: restarted
  register: nginx_restart
  ignore_errors: true

- fail: msg="{{ nginx_restart.stdout }} "
  when: "nginx_restart.changed == false and 'timed out' not in nginx_restart.msg"
