---
  - import_tasks: sudoer.yml
  - import_tasks: pi_os.yml
  - import_tasks: tmux.yml
  - import_tasks: ack.yml
  - import_tasks: zram.yml
  - import_tasks: log2ram.yml
  - import_tasks: disable_default_swap.yml
  - include_tasks: 
      file: set_fstab_opts.yml
      apply:
        vars:
          point: "/"
          opt: "commit=600"
          warn: false


