---
- name: Check if tmux is installed
  stat:
    path: /bin/tmux
  register: stat_tmux

- name: Install tmux
  become: true
  package:
    name: tmux
    state: present
  when: stat_tmux.stat.exists==false

- name: Check if .tmux.conf exists
  stat:
    path: ~/.tmux.conf
  register: tmuxconf

- name: Copy .tmux.conf
  template:
    src: .tmux.conf
    dest: ~/.tmux.conf
  when: not( tmuxconf.stat.exists )
        
