---
- name: Check if swap enabled
  shell: /usr/sbin/swapon -s | grep -v zram | wc -l
  register: swap_enabled
  changed_when: false

- name: Disable swap
  become: true
  command: "{{ item }}"
  with_items: 
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - update-rc.d dphys-swapfile disable
  when: swap_enabled.stdout == "2"

