- name: Make sure we have a 'wheel' group
  become: true
  group:
     name: wheel
     state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  become: true
  user:
    name="{{ansible_user}}"
    groups=wheel
    append=yes
    state=present

#- name: Set up authorized keys for the deployer user
#  authorized_key: user=deployer key="{{item}}"
#  with_file:
#    - /home/railsdev/.ssh/id_rsa.pub
