all:
  children:
    pis:
      hosts:
        pi0:
          ansible_host: 192.168.1.30
          ansible_user: pi
        pi4_0:
          ansible_host: 192.168.1.34
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
